#!/bin/sh
# Writes ios/Shared/Secrets.swift (gitignored) from ~/.config/clawd-dictate/env:
#   HARNESS_URL=https://…      the relay (word list lives there)
#   CAL_URL=https://…          the 📅 key
#   SLOP_URL=https://…         the 💻 key
#   DEEPGRAM_API_KEY=…         (falls back to clawd-harness/.clawd-harness.env)
#   DOCS_CREDENTIAL=…          the phone's read-only relay credential
# Nothing private — no key, no credential, no URL of yours — lives in the repo.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
exec python3 - "$HERE" <<'PY'
import json, os, sys
here = sys.argv[1]
home = os.path.expanduser("~")
def read_env(path):
    out = {}
    try:
        for line in open(path):
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                out[k.strip()] = v.strip().strip('"').strip("'")
    except OSError:
        pass
    return out
env = read_env(os.path.join(home, ".config", "clawd-dictate", "env"))
harness_env = read_env(os.path.join(os.environ.get("CLAWD_HARNESS", os.path.join(home, "clawd", "clawd-harness")), ".clawd-harness.env"))
key = env.get("DEEPGRAM_API_KEY") or harness_env.get("DEEPGRAM_API_KEY") or ""
missing = [k for k in ("HARNESS_URL", "CAL_URL", "SLOP_URL") if not env.get(k)]
if missing or not key:
    sys.exit(f"~/.config/clawd-dictate/env needs {', '.join(missing + ([] if key else ['DEEPGRAM_API_KEY']))} (see Secrets.swift.example)")
q = lambda s: json.dumps(str(s), ensure_ascii=False)   # emoji stay emoji — Swift has no \\uXXXX
with open(os.path.join(here, "Shared", "Secrets.swift"), "w") as f:
    f.write("// generated by gen-secrets.sh — never commit\n")
    f.write("enum Secrets {\n")
    f.write(f"    static let deepgramKey = {q(key)}\n")
    f.write(f"    static let docsCredential = {q(env.get('DOCS_CREDENTIAL', ''))}\n")
    f.write(f"    static let relay = {q(env['HARNESS_URL'].rstrip('/'))}\n")
    f.write(f"    static let calURL = {q(env['CAL_URL'])}\n")
    f.write(f"    static let slopURL = {q(env['SLOP_URL'])}\n")
    f.write("}\n")
print(f"wrote Shared/Secrets.swift (credential: {'yes' if env.get('DOCS_CREDENTIAL') else 'NONE'})")
PY
